import json

nb = {
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
  "language_info": {"name": "python", "version": "3.12.0"}
 },
 "cells": []
}

def md(cid, src):
    return {"cell_type": "markdown", "id": cid, "metadata": {}, "source": src}

def code(cid, src):
    return {"cell_type": "code", "execution_count": None, "id": cid,
            "metadata": {}, "outputs": [], "source": src}

nb["cells"] = [

md("md-title", [
    "# 10 · Skill Gap Analysis — IBM JobRole ↔ O*NET Skills\n",
    "\n",
    "**Project:** Enterprise HR AI  \n",
    "**Purpose:** For each of the 9 IBM JobRole values, retrieve top essential skills and\n",
    "top software tools from O*NET via the manually curated `jobrole_onet_mapping.csv`.\n",
    "\n",
    "> **Confidence caveats are printed alongside every result.**  \n",
    "> Low-confidence mappings are never presented without their caveat.  \n",
    "> The `very_low` confidence 'Manager' role receives a placeholder, not fabricated skill data.\n",
    "\n",
    "---"
]),

code("cell-imports", [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import os\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "PROC = os.path.join('..', 'data', 'processed')\n",
    "EXT  = os.path.join('..', 'data', 'external')\n",
    "\n",
    "# ── Load all data files ──────────────────────────────────────────────────────\n",
    "mapping   = pd.read_csv(os.path.join(EXT,  'jobrole_onet_mapping.csv'))\n",
    "occ       = pd.read_csv(os.path.join(PROC, 'occupation_master.csv'))\n",
    "essential = pd.read_csv(os.path.join(PROC, 'essential_skills_processed.csv'))\n",
    "software  = pd.read_csv(os.path.join(PROC, 'software_skills_processed.csv'))\n",
    "employees = pd.read_csv(os.path.join(PROC, 'employee_attrition_processed.csv'))\n",
    "\n",
    "print('=== FILE SHAPES ===')\n",
    "print(f'  jobrole_onet_mapping    : {mapping.shape}')\n",
    "print(f'  occupation_master       : {occ.shape}')\n",
    "print(f'  essential_skills        : {essential.shape}')\n",
    "print(f'  software_skills         : {software.shape}')\n",
    "print(f'  employee_attrition      : {employees.shape}')\n",
    "print()\n",
    "\n",
    "# ── Identify exact column names used for ranking ─────────────────────────────\n",
    "print('=== ESSENTIAL SKILLS: column used for ranking ===')\n",
    "# Filter to Importance scale only (Scale ID == 'IM') to avoid double-counting\n",
    "# with Level scale (Scale ID == 'LV'); ranking by 'Data Value'\n",
    "essential_im = essential[essential['Scale ID'] == 'IM'].copy()\n",
    "print(f'  Ranking column: \"Data Value\" (Importance score, Scale ID==\"IM\")')\n",
    "print(f'  Skill name column: \"Element Name\"')\n",
    "print(f'  After filtering to IM scale: {essential_im.shape[0]:,} rows')\n",
    "print()\n",
    "\n",
    "print('=== SOFTWARE SKILLS: ranking approach ===')\n",
    "# No numeric score in software_skills — software examples are listed flat.\n",
    "# Ranking by: Hot Technology=='Y' first, then In Demand=='Y', then alphabetical.\n",
    "# Actual software name is in 'Workplace Example' column.\n",
    "print('  No numeric score column in software_skills_processed.csv.')\n",
    "print('  Ranking: Hot Technology=Y first, then In Demand=Y, then alphabetical.')\n",
    "print('  Software name column: \"Workplace Example\"')\n",
    "print('  Category column: \"Element Name\"')\n",
    "\n",
    "# ── IBM roles ────────────────────────────────────────────────────────────────\n",
    "ibm_roles = mapping['ibm_job_role'].tolist()\n",
    "print()\n",
    "print(f'IBM job roles in mapping: {ibm_roles}')"
]),

md("md-per-role", [
    "---\n",
    "## Per-Role Skill Lookup\n",
    "\n",
    "For each role: confidence level printed first, then top 10 essential skills\n",
    "and top 10 software tools. `very_low` confidence Manager gets a placeholder only.\n"
]),

code("cell-lookup-functions", [
    "def get_top_essential(soc_code, n=10):\n",
    "    \"\"\"Return top-n essential skills by Data Value (Importance) for a SOC code.\"\"\"\n",
    "    subset = essential_im[essential_im['O*NET-SOC Code'] == soc_code]\n",
    "    if subset.empty:\n",
    "        return []\n",
    "    top = (subset\n",
    "           .sort_values('Data Value', ascending=False)\n",
    "           .drop_duplicates('Element Name')\n",
    "           .head(n))\n",
    "    return list(zip(top['Element Name'], top['Data Value'].round(2)))\n",
    "\n",
    "\n",
    "def get_top_software(soc_code, n=10):\n",
    "    \"\"\"Return top-n software tools for a SOC code.\n",
    "    Priority: Hot Technology=Y, then In Demand=Y, then alphabetical.\n",
    "    \"\"\"\n",
    "    subset = software[software['O*NET-SOC Code'] == soc_code].copy()\n",
    "    if subset.empty:\n",
    "        return []\n",
    "    # Create sort key: hot=0 > in_demand=1 > other=2\n",
    "    subset['_sort'] = 2\n",
    "    subset.loc[subset['In Demand'] == 'Y', '_sort'] = 1\n",
    "    subset.loc[subset['Hot Technology'] == 'Y', '_sort'] = 0\n",
    "    top = (subset\n",
    "           .sort_values(['_sort', 'Workplace Example'])\n",
    "           .drop_duplicates('Workplace Example')\n",
    "           .head(n))\n",
    "    return list(zip(top['Workplace Example'], top['Hot Technology'], top['In Demand']))\n",
    "\n",
    "\n",
    "def fmt_essential(pairs):\n",
    "    if not pairs:\n",
    "        return 'No data found for this SOC code.'\n",
    "    return ' | '.join(f'{name} ({val})' for name, val in pairs)\n",
    "\n",
    "\n",
    "def fmt_software(triples):\n",
    "    if not triples:\n",
    "        return 'No data found for this SOC code.'\n",
    "    parts = []\n",
    "    for name, hot, dem in triples:\n",
    "        tags = []\n",
    "        if hot == 'Y': tags.append('HOT')\n",
    "        if dem == 'Y': tags.append('IN-DEMAND')\n",
    "        tag_str = f' [{\"|\".join(tags)}]' if tags else ''\n",
    "        parts.append(f'{name}{tag_str}')\n",
    "    return ' | '.join(parts)\n",
    "\n",
    "\n",
    "# Employee count per IBM role\n",
    "role_counts = employees['JobRole'].value_counts().to_dict()\n",
    "\n",
    "print('Employee counts per IBM job role:')\n",
    "for role, count in sorted(role_counts.items()):\n",
    "    print(f'  {role:<35} {count:>4} employees')"
]),

code("cell-per-role-output", [
    "VERY_LOW_PLACEHOLDER = (\n",
    "    'Insufficient mapping confidence (very_low) — '\n",
    "    'use Department-level analysis instead (see Step 12). '\n",
    "    'O*NET skill data for this role is not reliable.'\n",
    ")\n",
    "\n",
    "# ── Main per-role loop ───────────────────────────────────────────────────────\n",
    "print('=' * 80)\n",
    "print('PER-ROLE SKILL LOOKUP (with confidence caveats)')\n",
    "print('=' * 80)\n",
    "\n",
    "for _, row in mapping.iterrows():\n",
    "    ibm_role   = row['ibm_job_role']\n",
    "    soc_code   = row['onet_soc_code']\n",
    "    onet_title = row['onet_title']\n",
    "    confidence = row['match_confidence']\n",
    "    emp_count  = role_counts.get(ibm_role, 0)\n",
    "\n",
    "    print(f'\\n{ibm_role}')\n",
    "    print(f'  Employees in dataset : {emp_count}')\n",
    "    print(f'  Mapped O*NET SOC     : {soc_code}  |  {onet_title}')\n",
    "    print(f'  Match Confidence     : [{confidence.upper()}]')\n",
    "\n",
    "    if confidence == 'very_low':\n",
    "        print(f'  Essential Skills     : *** {VERY_LOW_PLACEHOLDER} ***')\n",
    "        print(f'  Software Tools       : *** {VERY_LOW_PLACEHOLDER} ***')\n",
    "    else:\n",
    "        caveat = {\n",
    "            'medium': '[CAVEAT: approximate mapping — treat as directional guidance]',\n",
    "            'low':    '[CAVEAT: low-confidence mapping — use as broad reference only; results may not reflect actual role requirements]',\n",
    "        }.get(confidence, '')\n",
    "        print(f'  Confidence Note      : {caveat}')\n",
    "\n",
    "        ess = get_top_essential(soc_code, 10)\n",
    "        sw  = get_top_software(soc_code, 10)\n",
    "\n",
    "        print(f'  Top 10 Essential Skills (by Data Value/Importance, Scale ID=IM):')\n",
    "        if ess:\n",
    "            for i, (skill, val) in enumerate(ess, 1):\n",
    "                print(f'    {i:>2}. {skill:<45} {val}')\n",
    "        else:\n",
    "            print('    [No essential skills found for this SOC code]')\n",
    "\n",
    "        print(f'  Top 10 Software Tools (Hot Technology prioritized):')\n",
    "        if sw:\n",
    "            for i, (name, hot, dem) in enumerate(sw, 1):\n",
    "                tags = []\n",
    "                if hot == 'Y': tags.append('HOT')\n",
    "                if dem == 'Y': tags.append('IN-DEMAND')\n",
    "                tag_str = f' [{\"|\".join(tags)}]' if tags else ''\n",
    "                print(f'    {i:>2}. {name}{tag_str}')\n",
    "        else:\n",
    "            print('    [No software tools found for this SOC code]')\n",
    "\n",
    "print('\\n' + '=' * 80)"
]),

md("md-combined-table", [
    "---\n",
    "## Combined Output Table\n",
    "\n",
    "One row per IBM job role. Top 5 essential skills and top 5 software tools (space-constrained).\n",
    "Manager row deliberately shows the placeholder note instead of O*NET skill data.\n"
]),

code("cell-combined-table", [
    "records = []\n",
    "\n",
    "for _, row in mapping.iterrows():\n",
    "    ibm_role   = row['ibm_job_role']\n",
    "    soc_code   = row['onet_soc_code']\n",
    "    onet_title = row['onet_title']\n",
    "    confidence = row['match_confidence']\n",
    "    emp_count  = role_counts.get(ibm_role, 0)\n",
    "\n",
    "    if confidence == 'very_low':\n",
    "        top5_essential = VERY_LOW_PLACEHOLDER\n",
    "        top5_software  = VERY_LOW_PLACEHOLDER\n",
    "    else:\n",
    "        ess = get_top_essential(soc_code, 5)\n",
    "        top5_essential = ' | '.join(f'{s} ({v})' for s, v in ess) if ess else 'N/A'\n",
    "        sw = get_top_software(soc_code, 5)\n",
    "        top5_software = ' | '.join(n for n, h, d in sw) if sw else 'N/A'\n",
    "\n",
    "    records.append({\n",
    "        'ibm_job_role':       ibm_role,\n",
    "        'employee_count':     emp_count,\n",
    "        'onet_soc_code':      soc_code,\n",
    "        'onet_title':         onet_title,\n",
    "        'match_confidence':   confidence,\n",
    "        'top5_essential_skills': top5_essential,\n",
    "        'top5_software_tools':   top5_software,\n",
    "    })\n",
    "\n",
    "combined = pd.DataFrame(records)\n",
    "\n",
    "# ── Print table summary ───────────────────────────────────────────────────────\n",
    "print('=== COMBINED TABLE (all 9 roles) ===')\n",
    "print()\n",
    "for _, r in combined.iterrows():\n",
    "    print(f'Role            : {r[\"ibm_job_role\"]}  ({r[\"employee_count\"]} employees)')\n",
    "    print(f'O*NET SOC       : {r[\"onet_soc_code\"]}  ({r[\"match_confidence\"]} confidence)')\n",
    "    print(f'Top 5 Skills    : {r[\"top5_essential_skills\"]}')\n",
    "    print(f'Top 5 Software  : {r[\"top5_software_tools\"]}')\n",
    "    print()\n",
    "\n",
    "# ── Confirm Manager row has placeholder ──────────────────────────────────────\n",
    "print('=== MANAGER ROW VERIFICATION ===')\n",
    "mgr_row = combined[combined['ibm_job_role'] == 'Manager'].iloc[0]\n",
    "has_placeholder = VERY_LOW_PLACEHOLDER in mgr_row['top5_essential_skills']\n",
    "print(f'Manager confidence: {mgr_row[\"match_confidence\"]}')\n",
    "print(f'Manager essential_skills field: {mgr_row[\"top5_essential_skills\"][:100]}...')\n",
    "print(f'CONFIRMED placeholder present: {has_placeholder}')\n",
    "if not has_placeholder:\n",
    "    raise AssertionError('Manager row must show placeholder, not O*NET skill data!')"
]),

code("cell-save-csv", [
    "out_path = os.path.join(PROC, 'role_skill_profiles.csv')\n",
    "combined.to_csv(out_path, index=False, encoding='utf-8')\n",
    "print(f'Saved: {os.path.abspath(out_path)}')\n",
    "print(f'Shape: {combined.shape}')\n",
    "print(f'Size : {os.path.getsize(out_path):,} bytes')\n",
    "print()\n",
    "\n",
    "# Round-trip verify\n",
    "verify = pd.read_csv(out_path)\n",
    "assert len(verify) == 9, f'Expected 9 rows, got {len(verify)}'\n",
    "assert 'Manager' in verify['ibm_job_role'].values\n",
    "mgr_check = verify[verify['ibm_job_role'] == 'Manager']['top5_essential_skills'].iloc[0]\n",
    "assert 'Insufficient mapping confidence' in mgr_check, 'Manager row missing placeholder!'\n",
    "print('Round-trip verify: OK — 9 rows, Manager row has placeholder.')\n",
    "\n",
    "# Note on shared SOC code\n",
    "print()\n",
    "print('=== SHARED SOC CODE NOTE (logged in data_relationships.md Open Issue #1) ===')\n",
    "shared = combined.groupby('onet_soc_code')['ibm_job_role'].apply(list)\n",
    "for soc, roles in shared.items():\n",
    "    if len(roles) > 1:\n",
    "        print(f'  SOC {soc} shared by: {roles}')\n",
    "        print(f'  -> Their top5_essential_skills and top5_software_tools will be identical.')\n",
    "        print(f'  -> This is a mapping limitation, NOT a modeling error.')\n",
    "        print(f'  -> Must be labeled as such if surfaced in the Day 4 dashboard.')"
])

]

out_path = r'C:\Users\ASUS\Desktop\enterprise_hr_ai\notebooks\10_skill_gap_analysis.ipynb'
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print(f'Written: {out_path}')
